fragment SingleProduct on Product {
    id
    categories {
        id
        name
    }
    description
    images {
        alt
        height
        id
        url
        width
    }
    name
    price
    rating
}
