query CategoriesList($take: Int, $skip: Int) {
    categories(take: $take, skip: $skip) {
        data {
            id
            name
            description
            slug
        }
        meta {
            total
        }
    }
}

query CategoryProducts($slug: String) {
    category(slug: $slug) {
        id
        products {
            ...SingleProduct
        }
    }
}
