query ProductById($id: ID!) {
    product(id: $id) {
        ...SingleProduct
    }
}

query RelatedProducts {
    products(take: 4) {
        data {
            ...SingleProduct
        }
    }
}

query ProductReviews($id: ID!) {
    product(id: $id) {
        id
        reviews {
            ...ProductReview
        }
    }
}
